# global_costmap:
#    global_frame: odom         ##
#    robot_base_frame: base
#    update_frequency: 5.0      ##
#    publish_frequency: 3.0
#    static_map: false          ##
#    rolling_window: true       ##
#    resolution: 0.05
#    transform_tolerance: 1.0
#    map_type: costmap

global_costmap:
   global_frame: map         ##
   robot_base_frame: base_gazebo
   update_frequency: 15.0      ##
   publish_frequency: 10.0
   static_map: true
   # rolling_window: true     ## 使用滚动窗口
   resolution: 0.1
   transform_tolerance: 1.0
   map_type: costmap
   #添加插件
   plugins:
    - {name: static_layer,type: "costmap_2d::StaticLayer"}
    - {name: obstacle_layer,type: "costmap_2d::ObstacleLayer"}
    - {name: inflation_layer,type: "costmap_2d::InflationLayer"}
   #障碍物层
   obstacle_layer:
    enable: true
    observation_sources: scan robot_obstacles
    scan:
      topic: /scan
      sensor_frame: "" 
      data_type: LaserScan
      marking: true
      clearing: true
      obstacle_range: 2.5
      raytrace_range: 3.0
    robot_obstacles:
      topic: robot_obstacles_global
      data_type: PointCloud2
      sensor_frame: base_gazebo  # sensor frame（不能以/开头）
      marking: true
      clearing: true
      expected_update_rate: 0.0  # 设置为0表示不要求定期更新（按需发布）
      observation_persistence: 0.5  # 0.5秒后清除（当没有新数据时）
   #膨胀层
   inflation_layer:
    enable: true
    cost_scaling_factor: 10.0
    inflation_radius: 0.5