# global_costmap:
#    global_frame: odom         ##
#    robot_base_frame: base
#    update_frequency: 5.0      ##
#    publish_frequency: 3.0
#    static_map: false          ##
#    rolling_window: true       ##
#    resolution: 0.05
#    transform_tolerance: 1.0
#    map_type: costmap

global_costmap:
   global_frame: map         ##
   robot_base_frame: base
   update_frequency: 15.0      ##
   publish_frequency: 10.0
   static_map: true
   # rolling_window: true     ## 使用滚动窗口
   resolution: 0.05
   transform_tolerance: 0.5
   map_type: costmap
   #添加插件
   plugins:
    - {name: static_layer,type: "costmap_2d::StaticLayer"}
    - {name: obstacle_layer,type: "costmap_2d::ObstacleLayer"}
    - {name: inflation_layer,type: "costmap_2d::InflationLayer"}
   #膨胀层
   inflation_layer:
    enable: true
    cost_scaling_factor: 10.0
    inflation_radius: 0.5