# local_costmap:
#    global_frame: odom
#    robot_base_frame: base
#    update_frequency: 5.0
#    publish_frequency: 3.0
#    static_map: false
#    rolling_window: true
#    width: 3.0
#    height: 3.0
#    resolution: 0.05
#    transform_tolerance: 1.0
#    map_type: costmap
local_costmap:
   global_frame: odom
   robot_base_frame: base
   update_frequency: 30.0
   publish_frequency: 10.0
   #static_map: false
   rolling_window: true
   width: 15.0
   height: 15.0
   resolution: 0.05
   transform_tolerance: 1.0
   map_type: costmap
   #添加插件
   plugins:
    - {name: obstacle_layer,type: "costmap_2d::ObstacleLayer"}
    - {name: inflation_layer,type: "costmap_2d::InflationLayer"}
   #障碍物层
   obstacle_layer:
    enable: true
    observation_sources: scan
    scan:
      topic: /scan
      sensor_frame: "" 
      data_type: LaserScan
      marking: true
      clearing: true
      obstacle_range: 2.5
      raytrace_range: 3.0   
   #膨胀层
   inflation_layer:
    enable: true
    cost_scaling_factor:   10.0
    inflation_radius: 0.05